drv: fix unused variable
external/minigbm/drv.c:404:7: error: unused variable 'ret'
                int ret = drv_bo_mapping_destroy(bo);
                    ^

BUG=b:201325625
TEST=build latest in AOSP

Change-Id: I4070419aeae4054ed3eda084b810a3143a41b74f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/minigbm/+/3194819
Reviewed-by: Yiwei Zhang <zzyiwei@chromium.org>
Tested-by: Jason Macnak <natsu@google.com>
Commit-Queue: Yiwei Zhang <zzyiwei@chromium.org>